skip-check:
  - CKV_AWS_18  # S3 Bucket should have access logging configured - LoggingBucket is the destination bucket
  - CKV_AWS_53  # S3 Bucket should have block public ACLs enabled - CloudFront logging requires ACL access